### ISSUE TITLE
HTTP Error 404 when runing the demo

### ISSUE THREAD

**Issue by afalaize** [adavoudi/spdnet#8]
Hi!
We tried the demo in examples, and got line 48 of dataset.py in download:
`urllib.error.HTTPError: HTTP Error 404: Not Found`
This appens after the file data.zip is successfully downloaded.

**Comment by raj-shah** [comment]
Unfortunately, the dataloader has a few errors. The 404 Not Found error is due to an incorrect url for downloading the .mat file. Updating as such will fix the error:

```
downloads = [{'test': False, 'url': 'http://www.vision.ee.ethz.ch/~zzhiwu/codes/AFEW_SPD_data.zip',
              'dst': './data/AFEW', 'zip': True, 'filename': 'data.zip'},
             {'test': False, 'url': 'https://github.com/zzhiwu/SPDNet/raw/master/data/afew/spddb_afew_train_spd400_int_histeq.mat',
              'dst': './data/AFEW', 'zip': False, 'filename': 'spddb_afew_train_spd400_int_histeq.mat'}
             ]
```

Another error I noticed was FileNotFound when attempting to load batches during training, as the dataloader uses an incorrect path to get items. As the zip file extracts data to `./data/AFEW/spdface_400_inter_histeq/` folder and not `./data/AFEW/`, updating the `data_path` variable in `AFEWDataset` class' `__getitem__` function as such will fix this:

`data_path = os.path.join(self.base_path+'/spdface_400_inter_histeq', self.spd_path[index])`

**Comment by adavoudi** [comment]
Thank you @raj-shah for your contribution. I'll fix them.
